#!/usr/bin/env python3
"""
voice_install.py - Interactive Voice & TTS Configuration Wizard for Etherfields AI.
Sets up wake word engines, speech-to-text programs, text-to-speech engines,
and customized narrator/instruction voices.
"""

import os
import platform
import shutil
import subprocess
import sys
import urllib.request
from pathlib import Path

# Repo root is parent of voice directory (where this script resides)
REPO_ROOT = Path(__file__).resolve().parent.parent


# Color helpers
def print_success(msg):
    print(f"\033[92m✔ {msg}\033[0m")


def print_info(msg):
    print(f"\033[94mℹ {msg}\033[0m")


def print_warning(msg):
    print(f"\033[93m⚠ {msg}\033[0m")


def print_error(msg):
    print(f"\033[91m✘ {msg}\033[0m")


def ask_yes_no(question, default=False):
    suffix = " [Y/n]: " if default else " [y/N]: "
    val = input(f"\033[95m? {question}\033[0m" + suffix).strip().lower()
    if not val:
        return default
    return val.startswith("y")


def ask_input(question, default_val=None):
    suffix = f" [{default_val}]: " if default_val else ": "
    val = input(f"\033[95m? {question}\033[0m" + suffix).strip()
    return val if val else default_val


def download_file_with_progress(url, dest_path):
    print_info(f"Downloading {url} to {dest_path}...")
    dest_path = Path(dest_path)
    dest_path.parent.mkdir(parents=True, exist_ok=True)

    try:
        req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
        with urllib.request.urlopen(req) as response:
            total_size = int(response.info().get("Content-Length", 0))
            bytes_downloaded = 0
            with open(dest_path, "wb") as f:
                while True:
                    chunk = response.read(8192)
                    if not chunk:
                        break
                    f.write(chunk)
                    bytes_downloaded += len(chunk)
                    if total_size > 0:
                        percent = bytes_downloaded * 100 / total_size
                        print(
                            f"\rDownloading: {percent:.1f}% ({bytes_downloaded / (1024 * 1024):.1f}MB / {total_size / (1024 * 1024):.1f}MB)",
                            end="",
                            flush=True,
                        )
            print()
        print_success(f"Downloaded successfully.")
    except Exception as e:
        print_error(f"Download failed: {e}")
        raise e


def load_env_vars():
    env_vars = {}
    env_path = REPO_ROOT / ".env"
    if env_path.exists():
        with open(env_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, val = line.split("=", 1)
                    env_vars[key.strip()] = val.strip()
    return env_vars


def save_env_vars(new_vars):
    env_path = REPO_ROOT / ".env"
    # Load existing env vars to preserve ones we didn't touch
    existing_vars = {}
    ordered_keys = []

    if env_path.exists():
        with open(env_path, "r", encoding="utf-8") as f:
            for line in f:
                line_stripped = line.strip()
                if line_stripped and not line_stripped.startswith("#") and "=" in line_stripped:
                    key, val = line_stripped.split("=", 1)
                    key = key.strip()
                    existing_vars[key] = val.strip()
                    if key not in ordered_keys:
                        ordered_keys.append(key)

    # Merge
    merged_vars = existing_vars.copy()
    for k, v in new_vars.items():
        merged_vars[k] = str(v)
        if k not in ordered_keys:
            ordered_keys.append(k)

    # Write back
    with open(env_path, "w", encoding="utf-8") as f:
        f.write("# Generated by voice_install.py - DO NOT COMMIT TO GIT\n")
        # Ensure we write ETHERFIELDS_CUSTOM_DIR and ENABLE_VOICE first if they exist
        critical_keys = ["ETHERFIELDS_CUSTOM_DIR", "ENABLE_VOICE"]
        for ck in critical_keys:
            if ck in merged_vars:
                f.write(f"{ck}={merged_vars[ck]}\n")
                if ck in ordered_keys:
                    ordered_keys.remove(ck)

        for k in ordered_keys:
            if k not in critical_keys:
                f.write(f"{k}={merged_vars[k]}\n")

    print_success("Saved voice configuration to .env successfully.")


def main():
    print("=" * 60)
    print("🎙️  Etherfields AI Rule Master Voice Specific Configuration  🎙️")
    print("=" * 60)

    # Load current environment
    env = load_env_vars()

    new_configs = {}

    # 1. Wake Word Library Selection
    print("\n--- [Step 1: Wake Word Library Selection] ---")
    print("Choose the wake word library to listen for your activation phrase:")
    print("  1) nanowakeword (Recommended: highest accuracy, lowest CPU & memory footprint)")
    print("  2) openwakeword (Standard: wide model compatibility, solid default)")

    curr_ww = env.get("WAKE_WORD_ENGINE", "nanowakeword")
    ww_default = "1" if curr_ww == "nanowakeword" else "2"
    ww_choice = ask_input("Select wake word library (1-2)", ww_default)

    if ww_choice == "1":
        new_configs["WAKE_WORD_ENGINE"] = "nanowakeword"
        print_success("Selected wake word library: nanowakeword")
    else:
        new_configs["WAKE_WORD_ENGINE"] = "openwakeword"
        print_success("Selected wake word library: openwakeword")

    # 2. Speech to Text (STT) Program Selection
    print("\n--- [Step 2: Speech to Text (STT) Selection] ---")
    print("Choose the program used to transcribe your voice question:")
    print("  1) mlx-whisper (Apple Silicon native GPU acceleration, highly recommended for Mac)")
    print("  2) faster-whisper (Cross-platform standard, highly optimized CPU/GPU acceleration)")

    is_apple_silicon = sys.platform == "darwin" and platform.machine() == "arm64"
    stt_recommended = "1" if is_apple_silicon else "2"

    stt_choice = ask_input(f"Select Speech-to-Text program (1-2)", stt_recommended)

    if stt_choice == "1":
        new_configs["STT_PROGRAM"] = "mlx-whisper"
        print_success("Selected Speech-to-Text: mlx-whisper")
        selected_dep = '"mlx-whisper>=0.4.0",'
    else:
        new_configs["STT_PROGRAM"] = "faster-whisper"
        print_success("Selected Speech-to-Text: faster-whisper")
        selected_dep = '"faster-whisper>=1.0.0",'

    # Dynamically update voice_listener.py dependencies
    listener_path = REPO_ROOT / "voice" / "voice_listener.py"
    if listener_path.exists():
        with open(listener_path, "r", encoding="utf-8") as f:
            lines = f.readlines()

        with open(listener_path, "w", encoding="utf-8") as f:
            in_deps = False
            for line in lines:
                if line.strip() == "# dependencies = [":
                    in_deps = True
                    f.write(line)
                    continue
                if in_deps:
                    if line.strip() == "# ]":
                        in_deps = False
                        f.write(f"#     {selected_dep}\n")
                        f.write(line)
                    elif "whisper" not in line.lower():
                        # write existing non-whisper dependencies
                        f.write(line)
                else:
                    f.write(line)
        print_info("Updated voice_listener.py metadata dependencies automatically.")

    # 3. Text to Speech (TTS) System Selection
    print("\n--- [Step 3: Text to Speech (TTS) System] ---")
    print("Choose the engine used to narrate scripts and rule master instructions:")
    print(
        "  1) kokoro-onnx (Recommended: 100% offline, blazing-fast StyleTTS2, premium human quality)"
    )
    print("  2) openai (Online: cloud-based high fidelity voices, highly cost-effective)")
    print("  3) elevenlabs (Online: premium cloud-based hyper-realistic voices and custom cloning)")

    curr_tts = env.get("TTS_ENGINE", "kokoro")
    if curr_tts == "chatterbox":
        curr_tts = "kokoro"
    tts_default = "1" if curr_tts == "kokoro" else ("2" if curr_tts == "openai" else "3")
    tts_choice = ask_input("Select Text-to-Speech system (1-3)", tts_default)

    custom_dir_str = env.get(
        "ETHERFIELDS_LOCAL_DIR", env.get("ETHERFIELDS_CUSTOM_DIR", str(REPO_ROOT))
    )
    custom_dir = Path(custom_dir_str).expanduser().resolve()
    models_dir = custom_dir / "voice" / "models"

    if tts_choice == "1":
        new_configs["TTS_ENGINE"] = "kokoro"
        print_success("Selected TTS System: kokoro-onnx (Local Offline)")

        # Ensure Kokoro models are downloaded
        model_path = models_dir / "kokoro-v1.0.onnx"
        voices_path = models_dir / "voices-v1.0.bin"

        if not model_path.exists():
            print_warning("Kokoro ONNX model file missing. Downloading (~310MB)...")
            kokoro_model_url = "https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0/kokoro-v1.0.onnx"
            download_file_with_progress(kokoro_model_url, model_path)
        else:
            print_success(f"Kokoro ONNX model already cached at {model_path}")

        if not voices_path.exists():
            print_warning("Kokoro voices mapping file missing. Downloading (~15MB)...")
            kokoro_voices_url = "https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0/voices-v1.0.bin"
            download_file_with_progress(kokoro_voices_url, voices_path)
        else:
            print_success(f"Kokoro voices mapping already cached at {voices_path}")

    elif tts_choice == "2":
        new_configs["TTS_ENGINE"] = "openai"
        print_success("Selected TTS System: openai (Online)")

        curr_key = env.get("OPENAI_API_KEY", "")
        openai_key = ask_input("Enter your OpenAI API Key", curr_key)
        new_configs["OPENAI_API_KEY"] = openai_key

    else:
        new_configs["TTS_ENGINE"] = "elevenlabs"
        print_success("Selected TTS System: elevenlabs (Online)")

        curr_key = env.get("ELEVENLABS_API_KEY", "")
        eleven_key = ask_input("Enter your ElevenLabs API Key", curr_key)
        new_configs["ELEVENLABS_API_KEY"] = eleven_key

    # 4. Voice Model Configuration
    print("\n--- [Step 4: Voice Model Mappings] ---")
    tts_engine = new_configs["TTS_ENGINE"]

    if tts_engine == "kokoro":
        # Narration Voice (Kokoro)
        print("Select gender for Narration (Secret Scripts & Story elements):")
        print("  1) Male (Default - rich, atmospheric narrative voices)")
        print("  2) Female (Clear, warm narrative voices)")
        narrator_gender = ask_input("Select narration gender (1-2)", "1")

        if narrator_gender == "1":
            print("\nSelect a default Male voice for Narration:")
            print(
                "  1) bm_george (Default: rich, dramatic British male voice - highly recommended!)"
            )
            print("  2) am_adam (Alternative: standard American male storytelling voice)")
            print("  3) Custom (Specify any other Kokoro voice ID, e.g. bm_lewis, am_michael)")

            curr_narrator = env.get("VOICE_REF_NARRATIVE", "bm_george")
            narrator_default = (
                "1"
                if curr_narrator == "bm_george"
                else ("2" if curr_narrator == "am_adam" else "3")
            )
            narrator_choice = ask_input("Select narration voice (1-3)", narrator_default)

            if narrator_choice == "1":
                new_configs["VOICE_REF_NARRATIVE"] = "bm_george"
                print_success("Selected narrator voice: bm_george")
            elif narrator_choice == "2":
                new_configs["VOICE_REF_NARRATIVE"] = "am_adam"
                print_success("Selected narrator voice: am_adam")
            else:
                custom_voice = ask_input("Enter custom Kokoro voice ID", curr_narrator)
                new_configs["VOICE_REF_NARRATIVE"] = custom_voice
                print_success(f"Configured narrator voice: {custom_voice}")
        else:
            print("\nSelect a default Female voice for Narration:")
            print("  1) bf_emma (Default: crisp, dramatic British female voice)")
            print(
                "  2) af_heart (Alternative: popular warm, highly expressive American female voice)"
            )
            print("  3) Custom (Specify any other Kokoro voice ID, e.g. af_sarah, bf_isabella)")

            curr_narrator = env.get("VOICE_REF_NARRATIVE", "bf_emma")
            narrator_default = (
                "1" if curr_narrator == "bf_emma" else ("2" if curr_narrator == "af_heart" else "3")
            )
            narrator_choice = ask_input("Select narration voice (1-3)", narrator_default)

            if narrator_choice == "1":
                new_configs["VOICE_REF_NARRATIVE"] = "bf_emma"
                print_success("Selected narrator voice: bf_emma")
            elif narrator_choice == "2":
                new_configs["VOICE_REF_NARRATIVE"] = "af_heart"
                print_success("Selected narrator voice: af_heart")
            else:
                custom_voice = ask_input("Enter custom Kokoro voice ID", curr_narrator)
                new_configs["VOICE_REF_NARRATIVE"] = custom_voice
                print_success(f"Configured narrator voice: {custom_voice}")

        # Instruction Voice (Kokoro)
        print("\nSelect gender for Instructions (Rule Master & Gameplay advice):")
        print("  1) Female (Default - crisp, clear instructional voices)")
        print("  2) Male (Deep, authoritative instructional voices)")
        instructor_gender = ask_input("Select instruction gender (1-2)", "1")

        if instructor_gender == "1":
            print("\nSelect a default Female voice for Instructions:")
            print("  1) bf_emma (Default: crisp, clear British female instructional voice)")
            print("  2) af_sarah (Alternative: standard American female instructional voice)")
            print("  3) Custom (Specify any other Kokoro voice ID, e.g. af_bella, bf_isabella)")

            curr_instructor = env.get("VOICE_REF_INSTRUCTION", "bf_emma")
            instructor_default = (
                "1"
                if curr_instructor == "bf_emma"
                else ("2" if curr_instructor == "af_sarah" else "3")
            )
            instructor_choice = ask_input("Select instruction voice (1-3)", instructor_default)

            if instructor_choice == "1":
                new_configs["VOICE_REF_INSTRUCTION"] = "bf_emma"
                print_success("Selected instructor voice: bf_emma")
            elif instructor_choice == "2":
                new_configs["VOICE_REF_INSTRUCTION"] = "af_sarah"
                print_success("Selected instructor voice: af_sarah")
            else:
                custom_voice = ask_input("Enter custom Kokoro voice ID", curr_instructor)
                new_configs["VOICE_REF_INSTRUCTION"] = custom_voice
                print_success(f"Configured instructor voice: {custom_voice}")
        else:
            print("\nSelect a default Male voice for Instructions:")
            print("  1) bm_lewis (Default: standard British male voice)")
            print("  2) am_michael (Alternative: standard American male voice)")
            print("  3) Custom (Specify any other Kokoro voice ID, e.g. bm_george, am_adam)")

            curr_instructor = env.get("VOICE_REF_INSTRUCTION", "bm_lewis")
            instructor_default = (
                "1"
                if curr_instructor == "bm_lewis"
                else ("2" if curr_instructor == "am_michael" else "3")
            )
            instructor_choice = ask_input("Select instruction voice (1-3)", instructor_default)

            if instructor_choice == "1":
                new_configs["VOICE_REF_INSTRUCTION"] = "bm_lewis"
                print_success("Selected instructor voice: bm_lewis")
            elif instructor_choice == "2":
                new_configs["VOICE_REF_INSTRUCTION"] = "am_michael"
                print_success("Selected instructor voice: am_michael")
            else:
                custom_voice = ask_input("Enter custom Kokoro voice ID", curr_instructor)
                new_configs["VOICE_REF_INSTRUCTION"] = custom_voice
                print_success(f"Configured instructor voice: {custom_voice}")

    elif tts_engine == "openai":
        # Narration Voice (OpenAI)
        print("Select gender for Narration (Secret Scripts & Story elements):")
        print("  1) Male (Default - deep, atmospheric narration)")
        print("  2) Female (Clear, standard storytelling)")
        narrator_gender = ask_input("Select narration gender (1-2)", "1")

        if narrator_gender == "1":
            print("\nSelect a default Male voice for Narration:")
            print("  1) onyx (Default: deep, professional male)")
            print("  2) echo (Alternative: warm, friendly male)")
            print("  3) Custom (Specify any other OpenAI voice name, e.g. alloy, fable)")

            curr_narrator = env.get("VOICE_REF_NARRATIVE", "onyx")
            narrator_default = (
                "1" if curr_narrator == "onyx" else ("2" if curr_narrator == "echo" else "3")
            )
            narrator_choice = ask_input("Select narration voice (1-3)", narrator_default)

            if narrator_choice == "1":
                new_configs["VOICE_REF_NARRATIVE"] = "onyx"
                print_success("Selected narrator voice: onyx")
            elif narrator_choice == "2":
                new_configs["VOICE_REF_NARRATIVE"] = "echo"
                print_success("Selected narrator voice: echo")
            else:
                custom_voice = ask_input("Enter custom OpenAI voice name", curr_narrator)
                new_configs["VOICE_REF_NARRATIVE"] = custom_voice
                print_success(f"Configured narrator voice: {custom_voice}")
        else:
            print("\nSelect a default Female voice for Narration:")
            print("  1) alloy (Default: expressive, clear female)")
            print("  2) shimmer (Alternative: professional clear female)")
            print("  3) Custom (Specify any other OpenAI voice name, e.g. nova, fable)")

            curr_narrator = env.get("VOICE_REF_NARRATIVE", "alloy")
            narrator_default = (
                "1" if curr_narrator == "alloy" else ("2" if curr_narrator == "shimmer" else "3")
            )
            narrator_choice = ask_input("Select narration voice (1-3)", narrator_default)

            if narrator_choice == "1":
                new_configs["VOICE_REF_NARRATIVE"] = "alloy"
                print_success("Selected narrator voice: alloy")
            elif narrator_choice == "2":
                new_configs["VOICE_REF_NARRATIVE"] = "shimmer"
                print_success("Selected narrator voice: shimmer")
            else:
                custom_voice = ask_input("Enter custom OpenAI voice name", curr_narrator)
                new_configs["VOICE_REF_NARRATIVE"] = custom_voice
                print_success(f"Configured narrator voice: {custom_voice}")

        # Instruction Voice (OpenAI)
        print("\nSelect gender for Instructions (Rule Master & Gameplay advice):")
        print("  1) Female (Default - crisp, professional female)")
        print("  2) Male (Deep, authoritative male)")
        instructor_gender = ask_input("Select instruction gender (1-2)", "1")

        if instructor_gender == "1":
            print("\nSelect a default Female voice for Instructions:")
            print("  1) nova (Default: crisp, professional female)")
            print("  2) shimmer (Alternative: standard clear female)")
            print("  3) Custom (Specify any other OpenAI voice name, e.g. alloy, fable)")

            curr_instructor = env.get("VOICE_REF_INSTRUCTION", "nova")
            instructor_default = (
                "1" if curr_instructor == "nova" else ("2" if curr_instructor == "shimmer" else "3")
            )
            instructor_choice = ask_input("Select instruction voice (1-3)", instructor_default)

            if instructor_choice == "1":
                new_configs["VOICE_REF_INSTRUCTION"] = "nova"
                print_success("Selected instructor voice: nova")
            elif instructor_choice == "2":
                new_configs["VOICE_REF_INSTRUCTION"] = "shimmer"
                print_success("Selected instructor voice: shimmer")
            else:
                custom_voice = ask_input("Enter custom OpenAI voice name", curr_instructor)
                new_configs["VOICE_REF_INSTRUCTION"] = custom_voice
                print_success(f"Configured instructor voice: {custom_voice}")
        else:
            print("\nSelect a default Male voice for Instructions:")
            print("  1) onyx (Default: deep, authoritative male)")
            print("  2) echo (Alternative: warm, friendly male)")
            print("  3) Custom (Specify any other OpenAI voice name, e.g. alloy, fable)")

            curr_instructor = env.get("VOICE_REF_INSTRUCTION", "onyx")
            instructor_default = (
                "1" if curr_instructor == "onyx" else ("2" if curr_instructor == "echo" else "3")
            )
            instructor_choice = ask_input("Select instruction voice (1-3)", instructor_default)

            if instructor_choice == "1":
                new_configs["VOICE_REF_INSTRUCTION"] = "onyx"
                print_success("Selected instructor voice: onyx")
            elif instructor_choice == "2":
                new_configs["VOICE_REF_INSTRUCTION"] = "echo"
                print_success("Selected instructor voice: echo")
            else:
                custom_voice = ask_input("Enter custom OpenAI voice name", curr_instructor)
                new_configs["VOICE_REF_INSTRUCTION"] = custom_voice
                print_success(f"Configured instructor voice: {custom_voice}")

    else:  # elevenlabs
        # Narration Voice (ElevenLabs)
        print("Select gender for Narration (Secret Scripts & Story elements):")
        print("  1) Male (Default - deep, dramatic male storytelling)")
        print("  2) Female (Rich, highly expressive storytelling)")
        narrator_gender = ask_input("Select narration gender (1-2)", "1")

        if narrator_gender == "1":
            print("\nSelect a default Male voice ID for Narration:")
            print("  1) pNInz6obpg7ANgFlW75D (Rachel - standard male storytelling)")
            print("  2) Custom (Enter any custom ElevenLabs Voice ID)")

            curr_narrator = env.get("VOICE_REF_NARRATIVE", "pNInz6obpg7ANgFlW75D")
            narrator_default = "1" if curr_narrator == "pNInz6obpg7ANgFlW75D" else "2"
            narrator_choice = ask_input("Select narration voice (1-2)", narrator_default)

            if narrator_choice == "1":
                new_configs["VOICE_REF_NARRATIVE"] = "pNInz6obpg7ANgFlW75D"
                print_success("Selected narrator voice: Rachel")
            else:
                custom_voice = ask_input("Enter custom ElevenLabs Voice ID", curr_narrator)
                new_configs["VOICE_REF_NARRATIVE"] = custom_voice
                print_success(f"Configured narrator voice ID: {custom_voice}")
        else:
            print("\nSelect a default Female voice ID for Narration:")
            print("  1) 21m00Tcm4TlvDq8ikWAM (Rachel - standard expressive female)")
            print("  2) Custom (Enter any custom ElevenLabs Voice ID)")

            curr_narrator = env.get("VOICE_REF_NARRATIVE", "21m00Tcm4TlvDq8ikWAM")
            narrator_default = "1" if curr_narrator == "21m00Tcm4TlvDq8ikWAM" else "2"
            narrator_choice = ask_input("Select narration voice (1-2)", narrator_default)

            if narrator_choice == "1":
                new_configs["VOICE_REF_NARRATIVE"] = "21m00Tcm4TlvDq8ikWAM"
                print_success("Selected narrator voice: Rachel")
            else:
                custom_voice = ask_input("Enter custom ElevenLabs Voice ID", curr_narrator)
                new_configs["VOICE_REF_NARRATIVE"] = custom_voice
                print_success(f"Configured narrator voice ID: {custom_voice}")

        # Instruction Voice (ElevenLabs)
        print("\nSelect gender for Instructions (Rule Master & Gameplay advice):")
        print("  1) Female (Default - crisp, standard instructional female)")
        print("  2) Male (Deep, clear instructional male)")
        instructor_gender = ask_input("Select instruction gender (1-2)", "1")

        if instructor_gender == "1":
            print("\nSelect a default Female voice ID for Instructions:")
            print("  1) EXAVITQu4vr4xnSDxMaL (Bella - standard clear instructional female)")
            print("  2) Custom (Enter any custom ElevenLabs Voice ID)")

            curr_instructor = env.get("VOICE_REF_INSTRUCTION", "EXAVITQu4vr4xnSDxMaL")
            instructor_default = "1" if curr_instructor == "EXAVITQu4vr4xnSDxMaL" else "2"
            instructor_choice = ask_input("Select instruction voice (1-2)", instructor_default)

            if instructor_choice == "1":
                new_configs["VOICE_REF_INSTRUCTION"] = "EXAVITQu4vr4xnSDxMaL"
                print_success("Selected instructor voice: Bella")
            else:
                custom_voice = ask_input("Enter custom ElevenLabs Voice ID", curr_instructor)
                new_configs["VOICE_REF_INSTRUCTION"] = custom_voice
                print_success(f"Configured instructor voice ID: {custom_voice}")
        else:
            print("\nSelect a default Male voice ID for Instructions:")
            print("  1) pNInz6obpg7ANgFlW75D (Rachel - standard clear instructional male)")
            print("  2) Custom (Enter any custom ElevenLabs Voice ID)")

            curr_instructor = env.get("VOICE_REF_INSTRUCTION", "pNInz6obpg7ANgFlW75D")
            instructor_default = "1" if curr_instructor == "pNInz6obpg7ANgFlW75D" else "2"
            instructor_choice = ask_input("Select instruction voice (1-2)", instructor_default)

            if instructor_choice == "1":
                new_configs["VOICE_REF_INSTRUCTION"] = "pNInz6obpg7ANgFlW75D"
                print_success("Selected instructor voice: Rachel")
            else:
                custom_voice = ask_input("Enter custom ElevenLabs Voice ID", curr_instructor)
                new_configs["VOICE_REF_INSTRUCTION"] = custom_voice
                print_success(f"Configured instructor voice ID: {custom_voice}")

    # Save environment variables
    print("\n" + "-" * 60)
    save_env_vars(new_configs)

    # Sync the dependencies for the selected options!
    print_info(
        "Synchronizing environment and installing voice dependencies via `uv sync --extra voice`..."
    )
    try:
        subprocess.run(["uv", "sync", "--extra", "voice"], check=True)
        print_success("Voice environment synchronized successfully!")
    except subprocess.CalledProcessError as e:
        print_error(f"Failed to synchronize voice dependencies: {e}")
        print_warning("You may need to run 'uv sync --extra voice' manually.")

    print("=" * 60)
    print("\033[92m🎉  Voice configuration completed successfully!  🎉\033[0m")
    print("=" * 60)


if __name__ == "__main__":
    main()
